image: ${DOCKER_REGISTRY}/env/jdk8-maven339:latest
variables:
  PROJECT_GROUP: ${CI_PROJECT_NAMESPACE}
  PROJECT_NAME: ${CI_PROJECT_NAME}
  #MAVEN运行时参数, -U:强制检查所有snapshots更新; -B: batch-mode,批处理模式
  MAVEN_CLI_OPTS: "-U -B -Dspring.profiles.active=ci -Dconfig.server.enabled=false"
  VERSION: ${CI_BUILD_TAG}
  BUILD_DIR: /build/${PROJECT_GROUP}/${PROJECT_NAME}/${CI_PIPELINE_ID}
  RANCHER_URL_DEV_ENV: http://rancher.source3g.com:80/v1/projects/1a397175
  ACCESS_KEY_DEV_ENV: 079A5EDD7DDACF0836D8
  SECRET_KEY_DEV_ENV: PaxuVq9MwWXNvSTTc2zjPYZPXrQNP53TBN67ktZF

cache:
  key: ${CI_BUILD_REF}
  untracked: true
#定义CI阶段
stages:
  - build
  - package
  - deploy
#compile,package,install,deploy
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean
    - mvn $MAVEN_CLI_OPTS -U package
    # for test coverage
#    - '[ -r target/site/jacoco/index.html ] && cat target/site/jacoco/index.html'
  artifacts:
    paths:
      - target/*.jar
package:
  image: ${DOCKER_REGISTRY}/env/dind:latest
  stage: package
  script:
    - cp target/*.jar docker/${PROJECT_NAME}.jar
    - cd docker
    - sed -i 's#${DOCKER_REGISTRY}#'$DOCKER_REGISTRY'#g' Dockerfile
    - sed -i 's#${PROJECT_NAME}#'$PROJECT_NAME'#g' Dockerfile
    - DOCKER_REPO=${DOCKER_REGISTRY}/${PROJECT_GROUP}/${PROJECT_NAME}:${CI_BUILD_REF_NAME}
    # build docker image
    - docker build -t ${DOCKER_REPO} .
    # push至docker registry
    - docker push ${DOCKER_REPO}
  dependencies:
    - build
deploy:dev_env:
  image: ${DOCKER_REGISTRY}/env/rancher-compose:latest
  stage: deploy
  script:
    - cd docker
    - sed -i 's#${PROJECT_NAME}#'$PROJECT_NAME'#g' docker-compose.yml
    - rancher-compose --debug --url ${RANCHER_URL_DEV_ENV} --access-key ${ACCESS_KEY_DEV_ENV} --secret-key ${SECRET_KEY_DEV_ENV} -p ${PROJECT_GROUP} up -d --force-upgrade --confirm-upgrade
  only:
    - master
    - tags
  environment:
    name: dev
  dependencies:
    - package

