spring:
  thymeleaf:
    prefix: classpath:/templates
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: wxb
    password: wxbroot123456
    url: jdbc:mysql://10.31.146.112:3306/wechat_gateway?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.31.146.112
    port: 8009
    password: ceshi789
    timeout: 0
server:
  context-path: /wechatgateway
  port: 8080
logging:
  level:
    root: debug
wechat:
  openplatform:
    appid: wxc0e7c45bbe6d5459
    appsecret: bb7e865ed0710dbe7c6a9f77fb365dee
    redirectUrl: https://test.source3g.com/wechatgateway
    token: wxtest
    encodingAesKey: 1okj2shr3kfn1fnfs9fldnsche609dks8899sjqliye
  miniprogram:   
    requestdomain1: https://develop.source3g.com
    requestdomain2: https://preview.source3g.com
    wsrequestdomain1: https://develop.source3g.com
    wsrequestdomain2: https://preview.source3g.com
    uploaddomain1: https://develop.source3g.com
    uploaddomain2: https://preview.source3g.com
    downloaddomain1: https://develop.source3g.com
    downloaddomain2: https://preview.source3g.com
    webviewdomain1: https://develop.source3g.com
    webviewdomain2: https://preview.source3g.com
    #小程序版本号
    userversion: V0.0.1
fleetingtime:
  merchantInfoBySn: http://develop.source3g.com:57567/fleetingtime/tablecard/getBySn
push:
  url: http://develop.source3g.com:57560/push/push