spring:
  thymeleaf:
    prefix: classpath:/templates
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: wxb
    password: wxbroot123456
    url: jdbc:mysql://10.31.146.112:3306/wechat_gateway?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 10.31.146.112
    port: 8009
    password: ceshi789
    timeout: 0
server:
  context-path: /wechatgateway
  port: 8080
logging:
  level:
    root: debug
wechat:
  openplatform:
    appid: wxc0e7c45bbe6d5459
    appsecret: bb7e865ed0710dbe7c6a9f77fb365dee
    redirectUrl: http://develop.source3g.com
