spring:
  thymeleaf:
    prefix: classpath:/templates
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: wxb
    password: wxbroot123456
    url: jdbc:mysql://10.31.146.112:3306/wechat_gateway?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non-null
  redis:
    host: 10.31.146.112
    port: 8009
    password: ceshi789
    timeout: 0
server:
  context-path: /wechatgateway
  port: 8080
logging:
  level:
    root: debug
wechat:
  openplatform:
    appid: wx545e2458a2b577e8
    appsecret: c9222a297364f15438cd90142dbc2a60
    redirectUrl: http://develop.source3g.com/codecmanagement
    token: wxtest
    encodingAesKey: 1okj2shr3kfn1fnfs9fldnsche609dks8899sjqliye
  miniprogram:   
    requestdomain1: https://develop.source3g.com
    requestdomain2: https://preview.source3g.com
    wsrequestdomain1: https://develop.source3g.com
    wsrequestdomain2: https://preview.source3g.com
    uploaddomain1: https://develop.source3g.com
    uploaddomain2: https://preview.source3g.com
    downloaddomain1: https://develop.source3g.com
    downloaddomain2: https://preview.source3g.com
    webviewdomain1: https://develop.source3g.com
    webviewdomain2: https://preview.source3g.com
    userversion: V0.0.1
    templateMessageId: FciIs7kJ3WWr71W-qKiOmNiF74HdmxzYMJyrt7zGbgk
fleetingtime:
  merchantInfoBySn: http://develop.source3g.com:57567/fleetingtime/tablecard/getBySn
  merchantSnCount: http://develop.source3g.com:57567/fleetingtime/merchant/getSnCount
push:
  url: http://develop.source3g.com:57560/push/push
